---
apiVersion: v2
actions:
  - name: "Run alpine image to say hello world"
    events:
      - name: "sh.keptn.event.sayhello.triggered"
    tasks:
      - name: "copy Hello World in script"
        image: "ubuntu"
        files:
          - /job/helloWorld.sh
        cmd:
          - sh
        args:
          - "/keptn/job/helloWorld.sh"
  - name: "Run alpine image to say hello world S2"
    events:
      - name: "sh.keptn.event.saygoodbye.triggered"
    tasks:
      - name: "Say Bye World"
        image: "alpine"
        cmd:
          - echo
        args:
          - 'Goodbye, world!'
