---
apiVersion: v2
actions:
  - name: "Run alpine image to say hello world"
    events:
      - name: "sh.keptn.event.sayhello.triggered"
    tasks:
      - name: "Say Hello World"
        image: "alpine"
        cmd:
          - echo
        args:
          - 'Hello Team B'
      - name: "Say Hello World Again"
        image: "ubuntu"
        cmd:
          - echo
        args:
          - 'Hello Team A'
      - name: "Say Hello World in script"
        image: "alpine"
        cmd:
          - sh
        args:
          - "./helloWorld.sh"
