---
apiVersion: v2
actions:
  - name: "Run alpine image to say hello world"
    events:
      - name: "sh.keptn.event.sayhello.triggered"
    tasks:
      - name: "copy Hello World in script"
        image: "ubuntu"
        files:
          - /job/helloWorld.sh
        cmd:
          - sudo
        args:
          - "chmod 777 /keptn/job/helloWorld.sh"

