---
apiVersion: v2
actions:
  - name: "Run alpine image to say hello world"
    events:
      - name: "sh.keptn.event.sayhello.triggered"
    tasks:
      - name: "Run as different user"
        image: "alpine"
        securityContext:
          runAsUser: 7000
          runAsGroup: 9000
        cmd:
          - id
      - name: "Say Hello World in script"
        image: "alpine"
        files:
          - /job/helloWorld.sh
        cmd:
          - sh
        args:
          - -c
          - "/keptn/job/helloWorld.sh"
